### ISSUE TITLE
No Sky Q in Home App

### ISSUE THREAD

**Issue by karesake** [neilpatel121/homebridge-skyq-tvremote#2]
No Sky Accessory comes up in Home App ?

**Comment by neilpatel121** [comment]
> No Sky Accessory comes up in Home App ?

You don’t see a TV accessory, are you using Ethernet connection to your sky box?

**Comment by karesake** [comment]
No, Wireless. Another Sky Q Plugin (to turn it on and off) works.

**Comment by neilpatel121** [comment]
> No, Wireless. Another Sky Q Plugin (to turn it on and off) works.

So using the same underlying api to connect sky box, so if on and off work on other plugin this accessory should work, I haven’t test with WiFi but this shouldn’t be an issue.

can you sent me the homebridge logs

**Comment by neilpatel121** [comment]
Is this still an issue? Otherwise closing this?

**Comment by neilpatel121** [comment]
assume not issue here, closing this, please re-raise if still facing an issue with your homebridge logs
