### ISSUE TITLE
Switch channels via Siri

### ISSUE THREAD

**Issue by michel0271** [neilpatel121/homebridge-skyq-tvremote#20]
Hello, will it be possible to switch channels via Siri in a future version? I already have such a plug-in for my Sony TV and it is then implemented using scenes. Greetings Michel

**Comment by neilpatel121** [comment]
Can you please let us know the plugin name so we can see their source code as a reference implementation

**Comment by michel0271** [comment]
@neilpatel121 Thank you for your prompt reply!

With pleasure, Homebridge Bravia Tvos - https://github.com/SeydX/homebridge-bravia-tvos#readme


greetings michel

P.S: skyq-tvremote - great job !!!

**Comment by neilpatel121** [comment]
Thanks, what Siri command do you use to change the channel, can you type the command pls

**Comment by michel0271** [comment]
@neilpatel121 I've set up a scene for each channel.
And then I say over my homepod, Hey Siri activate RTL as an example. Everyone can determine that themselves when setting up the scene :-)

**Comment by michel0271** [comment]
@neilpatel121 In my case, of course, in German. But the Sony plug-in works in all languages, as I understand it.

**Comment by neilpatel121** [comment]
Ok I think I understand how you got it work, there is an alternative way you can do this, which I use all ready, I expose channels as switches in the home app, then you can use Siri to control the switch,

**Comment by neilpatel121** [comment]
Take a look at this https://github.com/AdamSwinden/homebridge-sky-q#readme

**Comment by neilpatel121** [comment]
This is what I use to use Siri to change sky channels

**Comment by EpicKris** [comment]
I've added the feature to switch channels.

Could you test `v1.2.0-beta.1` please?

**Comment by michel0271** [comment]
@EpicKris Very happy but how do I find the beta and how do I install it?

**Comment by EpicKris** [comment]
> @EpicKris Very happy but how do I find the beta and how do I install it?

Are you using Hombridge Config UI X?

**Comment by michel0271** [comment]
> > @EpicKris Very happy but how do I find the beta and how do I install it?
> 
> Are you using Hombridge Config UI X?

yes,  v4.41.0

**Comment by EpicKris** [comment]
> yes, v4.41.0

Go to the `Plugins` tab, select the tool (right of `Settings`), select `Install Previous Version`, select the latest beta, then select select `Install`.

You'll need to revert to the latest version manually after testing.

**Comment by michel0271** [comment]
> > yes, v4.41.0
> 
> Go to the `Plugins` tab, select the tool (right of `Settings`), select `Install Previous Version`, select the latest beta, then select select `Install`.
> 
> You'll need to revert to the latest version manually after testing.

Okay, so I installed and added it to HomeKit like the stable version. But unfortunately I get the message "No answer" But it looks good ;-)

![IMG_0190](https://user-images.githubusercontent.com/39130531/115963825-657b1100-a521-11eb-9c7e-a2a5ec9cf61a.PNG)
![IMG_0191](https://user-images.githubusercontent.com/39130531/115963828-66ac3e00-a521-11eb-936e-d07716a491b9.PNG)

**Comment by EpicKris** [comment]
Could you test `1.2.0-beta.3`?

**Comment by michel0271** [comment]
Hi, I installed the last beta and I can now turn Sky Q on and off again. So the connection is there. But there are no channels to be seen. greetings michel

**Comment by EpicKris** [comment]
Could you test `1.2.0-beta.5` please?

**Comment by michel0271** [comment]
> Could you test `1.2.0-beta.5` please?

Tested but unfortunately the same problem. There is a connection, it is possible to switch us on, but no station list. What is also wrong with the input sources, there is a station name that I can change, which doesn't make any sense at the moment.
![IMG_0196](https://user-images.githubusercontent.com/39130531/115990295-b0993080-a5c2-11eb-8ad2-cc5d936726a0.PNG)
![IMG_0195](https://user-images.githubusercontent.com/39130531/115990296-b1ca5d80-a5c2-11eb-8602-e8360d93bd1b.PNG)
![IMG_0193](https://user-images.githubusercontent.com/39130531/115990297-b262f400-a5c2-11eb-9b7b-1291d3922ba3.PNG)
![IMG_0194](https://user-images.githubusercontent.com/39130531/115990298-b262f400-a5c2-11eb-83b4-6ce36e3c8143.PNG)

**Comment by EpicKris** [comment]
Could you include your Homebridge logs please?

**Comment by michel0271** [comment]
> Could you include your Homebridge logs please?

ok. Please delete it after viewing ;-) 
[homebridge.log.txt](https://github.com/neilpatel121/homebridge-skyq-tvremote/files/6371764/homebridge.log.txt)

**Comment by EpicKris** [comment]
Have you tried removing and re-adding the TV since using the latest beta?

**Comment by michel0271** [comment]
> Have you tried removing and re-adding the TV since using the latest beta?

the TV? no why? It has nothing to do with the Sky Q Box, does it? But I deleted the Sky Q Box and added it again to test it. The Sky Q receiver is connected via HDMI 3 and the type of reception is cable

**Comment by EpicKris** [comment]
Could you include your Homebridge config.json please?

**Comment by michel0271** [comment]
> Could you include your Homebridge config.json please?

ok.
[config.json.txt](https://github.com/neilpatel121/homebridge-skyq-tvremote/files/6371795/config.json.txt)

**Comment by EpicKris** [comment]
The logging is a lot less chatty now thanks.

The issue with the inputs not appearing after a restart and requiring the home app to be killed and reopened persists. There is also an error thrown if you select the input:

```
[25/04/2021, 12:20:22] [skyq-tvremote] [Sky Q Mini] Set Input: 101
[25/04/2021, 12:20:22] [homebridge-skyq-tvremote] This plugin threw an error from the characteristic 'Active Identifier': Unhandled error thrown inside write handler for characteristic: input.split is not a function or its return value is not iterable. See https://git.io/JtMGR for more info.
```

_Originally posted by @benfysh in https://github.com/neilpatel121/homebridge-skyq-tvremote/issues/19#issuecomment-826308203_

**Comment by michel0271** [comment]
> The logging is a lot less chatty now thanks.
> 
> The issue with the inputs not appearing after a restart and requiring the home app to be killed and reopened persists. There is also an error thrown if you select the input:
> 
> ```
> [25/04/2021, 12:20:22] [skyq-tvremote] [Sky Q Mini] Set Input: 101
> [25/04/2021, 12:20:22] [homebridge-skyq-tvremote] This plugin threw an error from the characteristic 'Active Identifier': Unhandled error thrown inside write handler for characteristic: input.split is not a function or its return value is not iterable. See https://git.io/JtMGR for more info.
> ```
> 
> _Originally posted by @benfysh in [#19 (comment)](https://github.com/neilpatel121/homebridge-skyq-tvremote/issues/19#issuecomment-826308203)_

okay and that means what now? Can the problem be solved?

**Comment by EpicKris** [comment]
@michel0271 Could you visit http://192.168.178.40:9006/as/services and include the data here please?

**Comment by EpicKris** [comment]
@benfysh Could you test `1.2.0-beta.6` please?

**Comment by michel0271** [comment]
> @michel0271 Could you visit http://192.168.178.40:9006/as/services and include the data here please?

ok.
[service.txt](https://github.com/neilpatel121/homebridge-skyq-tvremote/files/6371830/service.txt)

**Comment by michel0271** [comment]
> @benfysh Could you test `1.2.0-beta.6` please?

testet... the same... no Channels, on/ off Works

**Comment by EpicKris** [comment]
Could you test `1.2.0-beta.7` please?

**Comment by michel0271** [comment]
> Could you test `1.2.0-beta.7` please?

tested, now we can no longer find the Sky Q Box on Homebridge and in the HomeApp

**Comment by EpicKris** [comment]
Could you include your Homebridge logs please? Please truncate them to only the latest run.

**Comment by michel0271** [comment]
> Could you include your Homebridge logs please? Please truncate them to only the latest run.

ok.
[homebridge.log.txt](https://github.com/neilpatel121/homebridge-skyq-tvremote/files/6371869/homebridge.log.txt)
[config.json.txt](https://github.com/neilpatel121/homebridge-skyq-tvremote/files/6371870/config.json.txt)

**Comment by EpicKris** [comment]
I'm not seeing any errors.

@benfysh Could you confirm this please?

**Comment by michel0271** [comment]
I installed Beta 7 again. Sky Q can now be seen in HomeBridge, but it does not appear in the HomeApp

**Comment by michel0271** [comment]
> I'm not seeing any errors.
> 
> @benfysh Could you confirm this please?

Now I have installed the normal version again and I can no longer add this to the Home App either. IP address has stayed the same from Sky Q. Could it be that Apple blocks it after too many attempts? Or that there are problems at Apple?

**Comment by EpicKris** [comment]
> Now I have installed the normal version again and I can no longer add this to the Home App either. IP address has stayed the same from Sky Q. Could it be that Apple blocks it after too many attempts? Or that there are problems at Apple?

Remember that TVs are external accessories, you may need to re-add it.

**Comment by michel0271** [comment]
> Remember that TVs are external accessories, you may need to re-add it.

nothing to be done, I installed the normal version 1.2.0 now. Sky Q Box can also be seen in Homebridge. But I can no longer add the box to the Home app.

**Comment by michel0271** [comment]
@EpicKris  Before it went without any problems. What's broken now?
![IMG_0197](https://user-images.githubusercontent.com/39130531/115994079-d7149700-a5d5-11eb-9ee2-96b86e93e553.PNG)

**Comment by EpicKris** [comment]
Try `Homebridge Settings` > `Remove Single Cached Accessory`.

**Comment by michel0271** [comment]
> Try `Homebridge Settings` > `Remove Single Cached Accessory`.

Okay ... the box is back in the Home App ... :-) Beta 7 reinstalled. When setting up the input sources it said Sky One HD, I left it that way. The Home App (see screenshot) says Sky One HD, if I press it, my box switches to channel 1100 (E! Enteraiment). All other channels are not available.
![IMG_0198](https://user-images.githubusercontent.com/39130531/115995120-48eedf80-a5da-11eb-8efe-d860c75f2ad9.PNG)

**Comment by benfysh** [comment]
Basic plugin functionality is working as expected (Beta 7). This issue still persists https://github.com/neilpatel121/homebridge-skyq-tvremote/issues/19#issuecomment-826276471

With regards to the channels as input. When you select ''BBC One Yorks' it seems to send 101 twice and sometimes ends up on 110 as opposed to 101. The input then gets stuck on ''BBC One Yorks' and requires a restart in order to reset.

Logs shown when selecting input are displayed below:

```
[25/04/2021, 14:15:16] [skyq-tvremote] [Sky Q Mini] Set Input: 101
[25/04/2021, 14:15:16] [skyq-tvremote] [Sky Q Mini] Set Input: 101
[25/04/2021, 14:15:16] [skyq-tvremote] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/local/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:146:95
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:4069) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/local/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:148:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:4069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by michel0271** [comment]
@EpicKris At least the channel is switched even if it is wrong. However, switching only worked once.

**Comment by EpicKris** [comment]
Could you test `1.2.0-beta.8` please?

**Comment by michel0271** [comment]
> Could you test `1.2.0-beta.8` please?

Tested, unfortunately the same again. When setting up in the Home App, Sky One HD was suggested which I left that way. This time the one-time switching does not work either. On / off works. I have a real guilty conscience, you are trying so hard for me ... sorry. You're great!

**Comment by EpicKris** [comment]
Please, don't apologise, it would be a great feature for this plugin.

Could you include your logs please?

**Comment by benfysh** [comment]
Beta 8 working here will change to 101 reliably now with no error in the logs. However it is still getting 'stuck' on ''BBC One Yorks' as the selected input showing on the tile after changing channels / power cycling the box and this remains even if you kill and reopen the home app requiring a homebridge restart in order to reset to blank.

I am not sure what the expected behaviour is or if you can get the currently tuned channel in order to correctly set the input if the channel is changed? Some way to reset the input selector after choosing a channel may work?

**Comment by michel0271** [comment]
> Please, don't apologise, it would be a great feature for this plugin.
> 
> Could you include your logs please?

Thank you, then we will continue to work on the matter :-)
[config.json.txt](https://github.com/neilpatel121/homebridge-skyq-tvremote/files/6372053/config.json.txt)
[homebridge.log.txt](https://github.com/neilpatel121/homebridge-skyq-tvremote/files/6372054/homebridge.log.txt)

**Comment by michel0271** [comment]
Somehow we have to manage that the channel list can be read out by the plug-in of the Sky Q receiver. At least that's how it works with the Sony TV OS plug-in. But maybe that's not even possible with the Sky Q Receiver?

**Comment by EpicKris** [comment]
> Somehow we have to manage that the channel list can be read out by the plug-in of the Sky Q receiver. At least that's how it works with the Sony TV OS plug-in. But maybe that's not even possible with the Sky Q Receiver?

I've grabbed the channel list from the Sky Q receiver, which is why you're seeing `Sky One HD` which s channel `100` for you.

Could you test `1.2.0-beta.9` please?

**Comment by michel0271** [comment]
> > Somehow we have to manage that the channel list can be read out by the plug-in of the Sky Q receiver. At least that's how it works with the Sony TV OS plug-in. But maybe that's not even possible with the Sky Q Receiver?
> 
> I've grabbed the channel list from the Sky Q receiver, which is why you're seeing `Sky One HD` which s channel `100` for you.
> 
> Could you test `1.2.0-beta.9` please?

Tested, Sky One HD set up as relaxed as suggested. It was switched once and even on the correct channel! :-) The whole thing did not work once, then unfortunately no longer. However, the other channels are not displayed. On / off works.

**Comment by benfysh** [comment]
@EpicKris is the intention to show all the channels from /as/services as inputs? (I am only seeing the first currently) I think there is a limit to the number of inputs to be displayed

From https://github.com/jsiegenthaler/homebridge-eosstb#readme
```
Input service. The input (TV channels) utilises one service per input. 
The maximum possible channels (inputs) are thus 100 - 3 = 97
```

An option may be to grab the favourites from a box via /as/services/favourites if they exist and use those?

**Comment by EpicKris** [comment]
> @EpicKris is the intention to show all the channels from /as/services as inputs? (I am only seeing the first currently) I think there is a limit to the number of inputs to be displayed

Yes, this exactly what we're trying to achieve, thank you for pointing out the limit as I'd forgotten about that.

> An option may be to grab the favourites from a box via /as/services/favourites if they exist and use those?

Could you provide me with data for the `/as/services/favourites` please?

**Comment by EpicKris** [comment]
Could you also test `1.2.0-beta.10` please?

**Comment by benfysh** [comment]
> Could you provide me with data for the `/as/services/favourites` please?

This is from the one box I have them set on:
```
{
   "favourites" : [
      {
         "lcn" : 1,
         "sid" : "1044"
      },
      {
         "lcn" : 2,
         "sid" : "4081"
      },
      {
         "lcn" : 3,
         "sid" : "2076"
      },
      {
         "lcn" : 4,
         "sid" : "4075"
      },
      {
         "lcn" : 5,
         "sid" : "4010"
      },
      {
         "lcn" : 6,
         "sid" : "2075"
      },
      {
         "lcn" : 7,
         "sid" : "4002"
      },
      {
         "lcn" : 8,
         "sid" : "2104"
      },
      {
         "lcn" : 9,
         "sid" : "4077"
      }
   ]
}
```

**Comment by michel0271** [comment]
> Could you also test `1.2.0-beta.10` please?

Wooooooow ... it seems to be working! I am so happy! Even if switching is very slow. Each channel number appears on the TV individually ... first as an example the 1 ... then the 2 ... then the 3. But it works! : :)
![Uploading IMG_0199.PNG…]()

**Comment by michel0271** [comment]
> Could you also test `1.2.0-beta.10` please?

![IMG_0199](https://user-images.githubusercontent.com/39130531/115997559-c539f080-a5e3-11eb-83ea-5bb8c7d504b9.PNG)
Wooooooow ... it seems to be working! I am so happy! Even if switching is very slow. Each channel number appears on the TV individually ... first as an example the 1 ... then the 2 ... then the 3. But it works! : :)

**Comment by benfysh** [comment]
`1.2.0-beta.10` is now showing the first 97 channels as inputs on all boxes (after killing and opening the home app after restarting homebridge. and you can change channels by selecting the inputs.

It still has the same behaviour in that the previously selected input persists even if the channel is changed or the box is power cycled.

**Comment by michel0271** [comment]
Good job! Many Thanks! I am very happy! I would like to continue to support you with the beta. Maybe we will get it to switch faster. The on-off function is also fast?

**Comment by EpicKris** [comment]
> It still has the same behaviour in that the previously selected input persists even if the channel is changed or the box is power cycled.

Is there an endpoint to get the current channel that you're aware of?

**Comment by michel0271** [comment]
https://user-images.githubusercontent.com/39130531/115998894-d259de00-a5e9-11eb-8378-b6fb19b9b28d.mov

👍🏼

**Comment by benfysh** [comment]
> > It still has the same behaviour in that the previously selected input persists even if the channel is changed or the box is power cycled.
> 
> Is there an endpoint to get the current channel that you're aware of?

not that I am aware of

**Comment by EpicKris** [comment]
> > Is there an endpoint to get the current channel that you're aware of?
> 
> not that I am aware of

Not that I could find either, I don't think there's a way around this issue without being able to grab that information.

**Comment by neilpatel121** [comment]
been having a look around, this like the HA community have managed to do this,

https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer

**Comment by neilpatel121** [comment]
can't find now typescript or js implementations, seems quite involved, with soap request, better reference implantation here..

https://github.com/4n0nD3v3l0p3r/Home_Assistant_SkyQ_MediaPlayer/blob/master/skyq/sky_remote.py

**Comment by EpicKris** [comment]
@neilpatel121 Great find, I'm going to create a separate library so we can utilise this, it even has device discovery.

**Comment by michel0271** [comment]
I have no idea what you're doing, but I'll be there ... First Beta Tester 😂👍🏼

**Comment by EpicKris** [comment]
So I can't test the Soap requests because I don't have access to a Sky Q yet.

**Comment by benfysh** [comment]
> So I can't test the Soap requests because I don't have access to a Sky Q yet.

Let me know if I can help in any way.

**Comment by EpicKris** [comment]
For now I've released this as is. #19 has been fixed and this feature is almost done. And will re-visit this again soon.

I have started developing a library at https://github.com/EpicKris/node-sky-q, you're welcome to test that as is if you'd like, however the Soap part hasn't been fully built out yet.

**Comment by michel0271** [comment]
Will you continue to work on the plugin? E.g. faster switching times? greetings michel

**Comment by EpicKris** [comment]
> Will you continue to work on the plugin? E.g. faster switching times? greetings michel

The actual speed of switching cannot be increased, it currently works by "backing up" and then entering the channel number as if it were a remote. I'm not aware of any other way of changing the channel currently.

**Comment by michel0271** [comment]
ok

**Comment by ngem1** [comment]
Can we have an option to not have channels listed? It shows as 97 off on my favourites page which means you cannot easily power cycle from the control centre. The LG web OS plug in for example has an option for channel control/volume control etc

**Comment by EpicKris** [comment]
Could you test `v1.3.0-beta.0`?

**Comment by benfysh** [comment]
> Could you test `v1.3.0-beta.0`?

Favourites are now being loaded as 'Inputs' on the box where I have them set instead of the first 100 channels. On boxes without favourites no 'Inputs' are being loaded. Not sure if this is what you are expecting?

The input is also not synced with the actual channel on the box assume you are not getting the state yet?

The issue persists that on the first open of the home all inputs are shown as switches as opposed to selectable inputs. Killing and reopening the home app resolves this.

![IMG_27AC1FF3A03B-1](https://user-images.githubusercontent.com/404201/120662838-5f157880-c481-11eb-9d00-4d83f5dde34f.jpeg)

**Comment by EpicKris** [comment]
So I'm trying to use the favourites from the Sky box for the input list instead of the first 100 channels.

Could you send me a full screenshot please?

**Comment by benfysh** [comment]
Sure:

After restarting homebridge only on first load of the home app:

![IMG_7EF33F3D66F0-1](https://user-images.githubusercontent.com/404201/120665803-02678d00-c484-11eb-9b33-01f6d952ec3b.jpeg)

After killing and reopening the home app.

![IMG_D3B9DD6FC4B1-1](https://user-images.githubusercontent.com/404201/120666361-6ee28c00-c484-11eb-8fe7-145e50cd92bc.jpeg)

**Comment by EpicKris** [comment]
The latest screenshot appears to be expected behaviour?

**Comment by EpicKris** [comment]
> Yes, it just requires you to kill and reopen the home app (even if wasn't running previously) in order to get the expected behaviour. Minor in the scheme of things and may be on the iOS as opposed to the plugin side.

Oh yes, I experienced the same issue, but does seem to be an iOS issue, tried with a couple of different devices.

**Comment by simon3163** [comment]
Hi Both,
Was this resolved - i can't see the inputs when i load this plugin into Home?

Thanks

**Comment by simon3163** [comment]
> This is what I use to use Siri to change sky channels

Does this still work, if so how?
Could you let me see the code?

**Comment by EpicKris** [comment]
@simon3163 Please open a new issue.
