### ISSUE TITLE
Error Message in log

### ISSUE THREAD

**Issue by gunti-2020** [neilpatel121/homebridge-skyq-tvremote#22]
**Describe Your Problem:**
After I habe installieren the Plugin, every Thinge was ok and ist works. Today I saw the error Messages in the log and I have no idea, what I can do

**Logs:**

(node:4418) UnhandledPromiseRejectionWarning: Error: Cannot add more than 100 services to a single accessory!
    at Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:453:13)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
    at /usr/local/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:152:42
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:147:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4418) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4418) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: homebridge-skyq-tvremote v1.3.0
* **Homebridge Version**: 1.3.4
* **Node.js Version**: 14.16.1
* **NPM Version**: 7.11.1
* **Operating System**:

**Comment by gunti-2020** [comment]
Is the issue Solveig in a Never Version?

**Comment by EpicKris** [comment]
Could you test `v1.3.0-beta.0`?

**Comment by gunti-2020** [comment]
Thanks for the update, now it is working Thanks and habe a nice dayJensGesendet mit der mobilen Mail AppAm 03.06.21 um 16:12 schrieb Kristian Matthews
                
            
            
                
                    Von: "Kristian Matthews" ***@***.***>Datum: 3. Juni 2021An: "neilpatel121/homebridge-skyq-tvremote" ***@***.***>Cc: "Author" ***@***.***>,"gunti-2020" ***@***.***>Betreff: Re: [neilpatel121/homebridge-skyq-tvremote] Error Message in log (#22)
                
                
Could you test v1.3.0-beta.0?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/neilpatel121/homebridge-skyq-tvremote/issues/22#issuecomment-853901127",
"url": "https://github.com/neilpatel121/homebridge-skyq-tvremote/issues/22#issuecomment-853901127",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
