### ISSUE TITLE
Partial Channel List

### ISSUE THREAD

**Issue by andypburke** [neilpatel121/homebridge-skyq-tvremote#27]
**Describe Your Problem:**

It appears that I only have a partial channel list and no way to remove or add channels.  When adding the accessory it seems to stop at ITV4 +1 and doesn't capture Sports or Movie channels.  It may be the same as the 100 device limit shown in the logs below. 

Is there a way to manually change the channels and channel numbers?

**Logs:**

(node:23028) UnhandledPromiseRejectionWarning: Error: Cannot add more than 100 services to a single accessory!
    at Accessory.addService (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:453:13)
    at PlatformAccessory.addService (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
    at /usr/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:152:42
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:147:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:23028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23028) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:23028) UnhandledPromiseRejectionWarning: Error: Cannot add more than 100 services to a single accessory!
    at Accessory.addService (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:453:13)
    at PlatformAccessory.addService (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
    at /usr/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:152:42
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:147:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:23028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Plugin Config:**

{
    "devices": [
        {
            "name": "Sky Q Main",
            "ipAddress": "192.168.86.250"
        },
        {
            "name": "Sky Q Mini",
            "ipAddress": "192.168.86.36"
        }
    ],
    "platform": "skyq-tvremote"
}

**Screenshots:**

Stops at ITV4+1 (see attached)
![IMG_1322](https://user-images.githubusercontent.com/4771045/120635969-f8826180-c464-11eb-8ed4-2c3b106fa94b.PNG)

**Environment:**

* **Plugin Version**: v1.3.0
* **Homebridge Version**: 1.3.4
* **Node.js Version**: v12.18.4
* **NPM Version**: 6.14.8
* **Operating System**: Raspbian

**Comment by EpicKris** [comment]
Could you test `v1.3.0-beta.1`?

**Comment by andypburke** [comment]
@EpicKris thanks for the update.  It looks as though this only provides favourite channels in the list. Is that by design?

**Comment by andypburke** [comment]
> @EpicKris thanks for the update. It looks as though this only provides favourite channels in the list. Is that by design?
> 
> If so it is still only a subset of my favourite channels. I seem to get the following error.
> 
> <img alt="Homebridge 2C14" width="414" src="https://user-images.githubusercontent.com/4771045/120685899-4cf30480-c498-11eb-822c-e84e452aa8b4.png">

Actually I have figured this out @EpicKris. For some reason it seems I had a gap in my favourites list which caused the channel list to bomb out when starting up.  I removed the empty slot and all works perfectly.  Thanks

**Comment by EpicKris** [comment]
Could you test `v1.4.0-beta.1` with a gap in your favourites if possible? This should resolve that.

**Comment by andypburke** [comment]
hi @EpicKris yes this worked in the beta version thanks.
