### ISSUE TITLE
BUG SKY Q MINI

### ISSUE THREAD

**Issue by MrNoooooooob** [neilpatel121/homebridge-skyq-tvremote#29]
Problems with the Sky Remote plugin and it doesn't work anymore if you add Sky Q Mini to the plugin !!!
<img width="1399" alt="Bildschirmfoto 2021-06-03 um 20 57 50" src="https://user-images.githubusercontent.com/70014906/120698162-f04f1400-c4ae-11eb-9bf0-bf4773035470.png">

**Comment by EpicKris** [comment]
Please submit a bug report: https://github.com/neilpatel121/homebridge-skyq-tvremote/issues/new?assignees=&labels=bug&template=bug-report.md&title=
