### ISSUE TITLE
Additional controls?

### ISSUE THREAD

**Issue by pjbarnett** [neilpatel121/homebridge-skyq-tvremote#3]
Hope you can help. When I swipe down on my phone and select the Q on the remote. I only have arrows with select, Play/Pause, Back and i. Is there any way to show additional controls i.e. guide etc?

Sorry if this is simple and I have missed it. I am just starting out on playing with Homebridge.

;)

**Comment by neilpatel121** [comment]
The custom TV plug written in HomeBridge only supports the controls you see..

See mappings below, I’ve mapped “I” as Sky Guide,

The volume up and down on the phone or ipad is sky channel up and down..

 case this.Characteristic.RemoteKey.ARROW_UP:
                return 'up';
              case this.Characteristic.RemoteKey.ARROW_DOWN:
                return 'down';
              case this.Characteristic.RemoteKey.ARROW_LEFT:
                return 'left';
              case this.Characteristic.RemoteKey.ARROW_RIGHT:
                return 'right';
              case this.Characteristic.RemoteKey.SELECT:
                return 'select';
              case this.Characteristic.RemoteKey.PLAY_PAUSE:
                return 'play';
              case this.Characteristic.RemoteKey.INFORMATION:
                return 'tvguide';
              case this.Characteristic.RemoteKey.BACK:
                return 'backup';
              case this.Characteristic.RemoteKey.EXIT:

**Comment by pjbarnett** [comment]
Thank you that's great and appreciate the quick reply.

Also is there a way of adding more than 1 Sky box? 

I'm actually a Control4 installer and doing this as a bit of test for all the most common features. So far Homebridge has actually outdone C4 as it integrates Ring and Nest cameras which currently cannot be done!

**Comment by neilpatel121** [comment]
I looked into Control4 4 years, back went against it cause I like to tinker, can go quite far with homebridge, I have texi alarm, hue, all light switches, tv, HDAnywhere matrix, harmony hub, hue sync box, roomba,Fibaro modules, Sonos,hikvision dvr, list goes on and on, all in homebridge..

Cool thing done with  ring and homebridge, when motion is detected on my front drive, my main tv switches matrix to cctv front door camera on my hikvision for 30 secs, then switches back to sky, and pauses/unpauses before and after switch.

Yes can have two sky boxes, I have sky q and sky mini box..

,
        {
            "name": "Sky Q",
            "platform": "skyq-tvremote",
            "ipaddress": "192.168.0.x"
        },
        {
            "name": "Sky Mini",
            "platform": "skyq-tvremote",
            "ipaddress": "192.168.0.x"
        }

**Comment by pjbarnett** [comment]
Thank you again for the quick reply. I was about to try as you mentioned for the 2nd box, so that's perfect.

Funny you mention HDanywhere as I've just emailed the owner of Pulse-Eight re integration for their Matrixes.
If I can kindly ask one more question, which Plugin do you use for the Sonos? I have the Sonos Arc in the main lounge and would like to include that.
As a side note, you seem to mentioning most of the products I install, Hik, Texe, hue. Unfortunately at home I have Rako lighting which doesn't seem to have any support at this moment in time as far as I can find but for my installs I do a lot of KNX which is supported. So I'm going to setup a little test bed with some KNX Dimmer and Relay units and play with that also.
Finally re Homebridge I couldn't believe I have also integrated my Mercedes Me, so I can check I locked the car!! 😀
Regards,
Paul

**Comment by neilpatel121** [comment]
Sonos i use homebridge plugin - https://github.com/ebaauw/homebridge-zp#readme

I also run a node instance for https://github.com/jishi/node-sonos-http-api, this is a http api over Sonos, so things like grouping, TTS is greats one, make annocements over Sonos, e.g. when night arm is set, front door open, motion at front door, can send this to any Sonos speaker in the home, using with the homebridge-http-switch


Never looked into Rako, did a quick google, seems they don’t have a plug, but the hub supports http api, you can do this yourself with the http switch plug

https://github.com/Supereg/homebridge-http-switch#readme - I use this a lot, anything supports http endpoint in home can end up as a switch in HomeKit, 
https://rakocontrols.com/media/1956/accessing-the-rako-bridge-v222.pdf

Wow, didn’t know cars have plugins, that is useful to know if the car is locked...  It’s good to hear that a home automation installer of control4, think good of homebridge and apple ecosystem.

**Comment by pjbarnett** [comment]
Many thanks again for your info. I will definitely be having a play with those plug-ins suggested. Yes the http api route is the way I am looking now.

**Comment by neilpatel121** [comment]
Resolved
