### ISSUE TITLE
Deep Standby

### ISSUE THREAD

**Issue by HomebridgeX** [neilpatel121/homebridge-skyq-tvremote#33]
**Is your feature request related to a problem? Please describe:**
When my Sky Q receiver is in deep standby, I get long error messages in the homebridge log.

**Describe the solution you'd like:**
Would it be possible that if the IP cannot be reached, the device is displayed as "off"?

**Describe alternatives you've considered:**
I don‘t know, if WOL is possible? 

**Additional context:**

**Comment by EpicKris** [comment]
Hello, please use the issue template: https://github.com/neilpatel121/homebridge-skyq-tvremote/issues/new/choose

This issue will be closed until updated.

**Comment by SmolSoftBoi** [comment]
I've given this some thought and if the device doesn't have an IP address, then it is unreachable as far as HomeKit is concerned. What's the use case for this scenario, I'm not sure of WoL is possible, you're welcome to test that and report back.
