### ISSUE TITLE
Can't add to Apple Home App

### ISSUE THREAD

**Issue by oaklandm** [neilpatel121/homebridge-skyq-tvremote#36]
**Describe The Bug:**
I have successfully added the plugin to Homebridge and the accessories are showing. When I try to add to the Home app and enter the HomeKit code the device doesn't show up to be added. I have tried installing an older version of the plugin to see if that works but it didn't.
I did have Sky Q No Logs installed also and that worked fine, I did remove that plugin in case it was messing with this plugin but it didn't make any difference.

**To Reproduce:**
Try to add to HomeKit App

**Expected behavior:**
Should be able to add Sky Q to HomeKit to work as remote

**Logs:**

```
Loaded plugin: homebridge-skyq-tvremote@1.4.1
[26/11/2021, 13:01:22] Registering platform 'homebridge-skyq-tvremote.skyq-tvremote'
[26/11/2021, 13:01:22] ---
[26/11/2021, 13:01:22] Loading 3 platforms...
[26/11/2021, 13:01:22] [Config] Initializing config platform...
[26/11/2021, 13:01:22] [Config] Running in Service Mode
[26/11/2021, 13:01:22] [Nest] Initializing Nest platform...
[26/11/2021, 13:01:22] [skyq-tvremote] Initializing skyq-tvremote platform...
[26/11/2021, 13:01:22] [skyq-tvremote] Sky TV platform finished initializing!
[26/11/2021, 13:01:23] TV 1 A1CC is running on port 34505.
[26/11/2021, 13:01:23] Please add [TV 1 A1CC] manually in Home app. Setup Code:
```

**Plugin Config:**

```json
{
            "devices": [
                {
                    "ipAddress": "192.168.1.**"
                }
            ],
            "platform": "skyq-tvremote"
        }
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.4.1
* **Homebridge Version**:  1.3.8
* **Node.js Version**:  14.8.1
* **NPM Version**:  6.14.15
* **Operating System**:  Raspbian

**Comment by oaklandm** [comment]
Reset Homebridge and HomeKit and now is working

**Comment by AATTARD03** [comment]
Thought I should say this for anyone else unable to add their boxes - you probably don’t need to reset Homebridge. 
1. First uninstall the plugin and restart Homebridge.
2. Go to “ ≡ →  ⁝ → Homebridge Settings → Unpair Bridges / Cameras / TVs / External Accessories“ and remove any accessories linked to the plug-in; I.e. sky q boxes or bridges for the plug-in.
3. Restart Homebridge and configure the plugin like new - and ideally put it on a child bridge as it is an old plugin so could break.
4. Having re configured it restart Homebridge for a final time and your accessories should be there in the home app.

Hope this helps anyone else getting frustrated 👍
