### ISSUE TITLE
Change favourite channels / rewind/fast-forward

### ISSUE THREAD

**Issue by benkayuk** [neilpatel121/homebridge-skyq-tvremote#37]
Hi, thanks for a great plugin.

I just have 2 questions.

1. How can I change the "inputs" that appear after a long-press of the device in Home app? I can change the channel names / but the channel nunber inputs seem to be hard-coded...
2. In the control centre remote device, there are no controls for rewind / fast-forward. Can those be added?

**Comment by benkayuk** [comment]
Ignore point 1, I discovered that it dynamically pulls the "favourites" as set on the Sky Q box itself...very cool.

Anything on point 2?

**Comment by eukshark** [comment]
Hi, i am looking at using Siri to change channels what did you to set up yours benkayuk

**Comment by SmolSoftBoi** [comment]
The rewind and fast-forward controls are set in the code, anyone else know why these may not show in HomeKit?
