### ISSUE TITLE
Can't see how to use Favourite channels

### ISSUE THREAD

**Issue by the-etk** [neilpatel121/homebridge-skyq-tvremote#39]
I've managed to get the plugin installed and working nicely with my Sky Q box.  It will happily turn the box on and off using either the Home app or the remote control device in control centre.

I've got five favourite channels set up on my sky box which I can see if I go into the settings of the Sky Q Accessory in the Home app, but I can't make any of them change channels - if I tap them they just open a settings screen for that channel, they don't activate the new channel.  It looks like all five channels are "on" whenever the main accessory is "on".  Am I doing something wrong?

**Comment by benfysh** [comment]
If you force quit and reopen the home app they will correctly show as inputs. You will need to do this every time homebridge restarts not sure if this a homebridge / plugin issue or a feature of the home app.

**Comment by the-etk** [comment]
perfect, thanks that's worked! Really good plugin
