### ISSUE TITLE
Multiple Sky Q Devices

### ISSUE THREAD

**Issue by EpicKris** [neilpatel121/homebridge-skyq-tvremote#5]
Allow multiple Sky Q devices.

Example Configuration:
```json
{
    "name": "Sky Q",
    "accessories": [
        {
            "name": "Living Room Sky Q",
            "ipAddress": "192.168.0.2"
        },
        {
            "name": "Bedroom Sky Q",
            "ipAddress": "192.168.0.3"
        }
    ],
    "platform": "skyq-tvremote"
}
```

**Comment by neilpatel121** [comment]
this should be an issue, i use with two sky boxes at my place, write your config like this

{
            "name": "Living Room Sky Q",
            "platform": "skyq-tvremote",
            "ipaddress": "192.168.0.2"
        },
        {
            "name": "Bedroom Sky Q",
            "platform": "skyq-tvremote",
            "ipaddress": "192.168.0.3"
        }

**Comment by EpicKris** [comment]
> this shouldnt be an issue, i use with two sky boxes at my place, write your config like this

Doesn't this load 2 instances of the same plugin?

**Comment by neilpatel121** [comment]
Yeh it doesn’t, isn’t the best implementation it something I knocked up quickly to get the functionality i required. Can be done in a single plugin, think the repo is open happy for you to contribute

**Comment by benfysh** [comment]
The readme has been updated to show the current config required to enable multiple boxes.
